#!/bin/bash -e

echo "Starting do/build_container"

if [ -z "${VERSION}" ]; then
    echo "VERSION must be set!"
    exit 1
fi

if [ -z "${DOCKER_IMAGE}" ]; then
    echo "DOCKER_IMAGE must be set!"
    exit 1
fi

if [ -z "${DOCKERFILE_FOLDER}" ]; then
    echo "DOCKERFILE_FOLDER must be set!"
    exit 1
fi

SONAR_TOKEN=$(credstash get jenkins.ec2.sonarqube_webtoken)

docker build -f deploy/docker/${DOCKERFILE_FOLDER}/Dockerfile . --build-arg ENVIRONMENT=development --build-arg SONAR_TOKEN=${SONAR_TOKEN} --build-arg VERSION=${VERSION} -t "${DOCKER_IMAGE}:${VERSION}" -t "${DOCKER_IMAGE}:latest"

if [[ "${DOCKERFILE_FOLDER}" != "monorepo" ]]; then
    docker build -f deploy/docker/${DOCKERFILE_FOLDER}/Dockerfile . --build-arg ENVIRONMENT=staging --build-arg VERSION=${VERSION} -t "${DOCKER_IMAGE}-staging:${VERSION}" -t "${DOCKER_IMAGE}-staging:latest"
    docker build -f deploy/docker/${DOCKERFILE_FOLDER}/Dockerfile . --build-arg ENVIRONMENT=production --build-arg VERSION=${VERSION} -t "${DOCKER_IMAGE}-production:${VERSION}" -t "${DOCKER_IMAGE}-production:latest"
fi

echo "Completed do/build_container"