#!/bin/bash -e

echo "Starting do/deploy_container"

if [ -z "${VERSION}" ]; then
    echo "VERSION must be set!"
    exit 1
fi

if [ -z "${DOCKER_IMAGE}" ]; then
    echo "DOCKER_IMAGE must be set!"
    exit 1
fi

if [ -z "${DOCKERFILE_FOLDER}" ]; then
    echo "DOCKERFILE_FOLDER must be set!"
    exit 1
fi

docker push "${DOCKER_IMAGE}:${VERSION}"
docker push "${DOCKER_IMAGE}:latest"

if [[ "${DOCKERFILE_FOLDER}" != "monorepo" ]]; then
    docker push "${DOCKER_IMAGE}-staging:${VERSION}"
    docker push "${DOCKER_IMAGE}-staging:latest"
    docker push "${DOCKER_IMAGE}-production:${VERSION}"
    docker push "${DOCKER_IMAGE}-production:latest"
fi

echo "Completed do/deploy_container"