export const PPATypes = {
    filters: {
        SAVE: "PPA_FILTERS_SAVE"
    },
    dimensions: {
        FIRST_LIST_REQUEST: "PPA_DIMENSIONS_FIRST_LIST_REQUEST",
        FIRST_LIST_SUCCESS: "PPA_DIMENSIONS_FIRST_LIST_SUCCESS",
        FIRST_LIST_FAILURE: "PPA_DIMENSIONS_FIRST_LIST_FAILURE",
        FIRST_LIST_SELECT: "PPA_DIMENSIONS_FIRST_LIST_SELECT",
        SECOND_LIST_REQUEST: "PPA_DIMENSIONS_SECOND_LIST_REQUEST",
        SECOND_LIST_SUCCESS: "PPA_DIMENSIONS_SECOND_LIST_SUCCESS",
        SECOND_LIST_FAILURE: "PPA_DIMENSIONS_SECOND_LIST_FAILURE",
        SECOND_LIST_SELECT: "PPA_DIMENSIONS_SECOND_LIST_SELECT",
        SWAP: "PPA_DIMENSIONS_SWAP",
    },
    grid: {
        REQUEST: "PPA_GRID_REQUEST",
        SUCCESS: "PPA_GRID_SUCCESS",
        FAILURE: "PPA_GRID_FAILURE",
        RESET: "PPA_GRID_RESET",
        SORT: "PPA_GRID_SORT",
        TOGGLE_CHILDREN: "PPA_GRID_TOGGLE_CHILDREN",
        TOGGLE_ALL_CHILDREN: "PPA_GRID_TOGGLE_ALL_CHILDREN"
    }
};
